name: Build & deploy Zola site

on:
  push:
    branches: [$default-branch]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Install Aola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.1

  build:
    runs-on: ubuntu-latest
    needs: setup
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Build site
        id: zola-build
        run: zola build

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          path: public

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
