on: push
name: Build & deploy Zola site

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'


    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install Rustup + Cargo
        id: install-toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Checkout Zola
        id: checkout-zola
        uses: actions/checkout@v4
        with:
          repository: getzola/zola
          ref: v0.19.2
          path: .zola

      - name: Install Zola
        id: install-zola
        run: cargo install --path .zola

      - name: Build site
        id: zola-build
        run: zola build

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          path: public

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
